# Generated by Django 3.2.7 on 2021-12-02 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='原材料名称')),
                ('category', models.CharField(choices=[('VG', '蔬菜'), ('MT', '肉类'), ('CND', '调料'), ('RNO', '米面油'), ('DSP', '低值易耗')], default='VG', max_length=3, verbose_name='原材料分类')),
                ('ratio', models.FloatField(default=1, verbose_name='转化率')),
                ('price', models.FloatField(verbose_name='单价(元/斤或个)')),
            ],
            options={
                'verbose_name': '原材料',
                'verbose_name_plural': '原材料',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('type', models.CharField(choices=[('CK', '中央厨房'), ('DH', '食堂')], default='DH', max_length=2, verbose_name='项目类型')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='SDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='菜品名称')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
            },
        ),
        migrations.CreateModel(
            name='SDish2Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=200, verbose_name='标准名称')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.sdish', verbose_name='菜品名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '菜品标准',
                'verbose_name_plural': '菜品标准',
            },
        ),
        migrations.CreateModel(
            name='SDish2StandardIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='重量')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ingredient', verbose_name='原材料名称')),
                ('sdish2standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='common.sdish2standard')),
            ],
            options={
                'verbose_name': '此标准的原材料',
                'verbose_name_plural': '此标准的原材料',
            },
        ),
    ]
