# Generated by Django 3.2.7 on 2021-12-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': '原材料', 'verbose_name_plural': '原材料'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='sdish',
            options={'verbose_name': '菜品', 'verbose_name_plural': '菜品'},
        ),
    ]
