# Generated by Django 3.2.7 on 2021-12-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20211222_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('VG', '蔬果'), ('MT', '肉类'), ('TF', '豆制品'), ('CND', '调料'), ('DRY', '干货'), ('RNO', '米面油'), ('DSP', '低值易耗')], default='VG', max_length=3, verbose_name='分类'),
        ),
    ]
