# Generated by Django 3.2.10 on 2022-01-30 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_ingredient_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.CreateModel(
            name='IngredientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='单价')),
                ('effective_date', models.DateField(default=datetime.date.today, verbose_name='生效日期')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ingredient', verbose_name='原材料')),
            ],
            options={
                'verbose_name': '原材料价格',
                'verbose_name_plural': '原材料价格',
            },
        ),
    ]
