# Generated by Django 3.2.10 on 2022-01-30 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20220130_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientprice',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='common.ingredient', verbose_name='原材料'),
        ),
    ]
