# Generated by Django 3.2.10 on 2022-01-17 12:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_alter_ingredient_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryInList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('comments', models.TextField(verbose_name='评论')),
                ('status', models.CharField(choices=[('EDT', '正在编辑'), ('SBM', '已提交'), ('APR', '通过'), ('REJ', '未通过')], default='EDT', max_length=3, verbose_name='状态')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.project', verbose_name='项目')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryOutListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='数量')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.ingredient', verbose_name='原材料')),
                ('out_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_items', to='inventory.inventoryinlist')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryOutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('comments', models.TextField(verbose_name='评论')),
                ('status', models.CharField(choices=[('EDT', '正在编辑'), ('SBM', '已提交'), ('APR', '通过'), ('REJ', '未通过')], default='EDT', max_length=3, verbose_name='状态')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.project', verbose_name='项目')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryInListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='数量')),
                ('in_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_items', to='inventory.inventoryinlist')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.ingredient', verbose_name='原材料')),
            ],
        ),
    ]
