# Generated by Django 3.2.10 on 2022-01-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryinlist',
            options={'verbose_name': '入库单', 'verbose_name_plural': '入库单'},
        ),
        migrations.AlterModelOptions(
            name='inventoryoutlist',
            options={'verbose_name': '出库单', 'verbose_name_plural': '出库单'},
        ),
        migrations.AlterField(
            model_name='inventoryinlist',
            name='status',
            field=models.CharField(choices=[('EDT', '编辑中'), ('SBM', '已提交'), ('APR', '通过'), ('REJ', '未通过'), ('RED', '重新编辑中'), ('RSB', '已重新提交')], default='EDT', max_length=3, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='inventoryoutlist',
            name='status',
            field=models.CharField(choices=[('EDT', '编辑中'), ('SBM', '已提交'), ('APR', '通过'), ('REJ', '未通过'), ('RED', '重新编辑中'), ('RSB', '已重新提交')], default='EDT', max_length=3, verbose_name='状态'),
        ),
    ]
