# Generated by Django 3.2.10 on 2022-01-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220120_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryinlist',
            options={'permissions': [('edit_comments', 'Can edit comments')], 'verbose_name': '入库单', 'verbose_name_plural': '入库单'},
        ),
    ]
