# Generated by Django 3.2.7 on 2021-11-30 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目采购清单',
                'verbose_name_plural': '                                                                                              项目采购清单',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
            ],
            options={
                'verbose_name': '采购清单汇总',
                'verbose_name_plural': '                                                                                             采购清单汇总',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderSummaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='数量')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ingredient', verbose_name='原材料')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseordersummary')),
            ],
            options={
                'verbose_name': '采购品',
                'verbose_name_plural': '采购品',
            },
        ),
        migrations.CreateModel(
            name='ProjectPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='数量')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.ingredient', verbose_name='原材料')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.projectpurchaseorder')),
            ],
            options={
                'verbose_name': '项目采购品',
                'verbose_name_plural': '项目采购品',
            },
        ),
    ]
