# Generated by Django 3.2.7 on 2021-12-02 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpurchaseorder',
            options={'verbose_name': '项目采购清单', 'verbose_name_plural': '项目采购清单'},
        ),
        migrations.AlterModelOptions(
            name='purchaseordersummary',
            options={'verbose_name': '采购清单汇总', 'verbose_name_plural': '采购清单汇总'},
        ),
        migrations.AlterField(
            model_name='projectpurchaseorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.projectpurchaseorder'),
        ),
    ]
