# Generated by Django 3.2.10 on 2022-02-24 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_projectpurchaseorder_status'),
        ('common', '0005_alter_ingredientprice_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_settings', to='common.project', verbose_name='项目')),
                ('daily_purchasing_budget', models.FloatField(verbose_name='每日采购成本上限')),
            ],
            options={
                'verbose_name': '项目采购设置',
                'verbose_name_plural': '项目采购设置',
            },
        ),
    ]
