# Generated by Django 3.2.7 on 2021-09-15 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CKProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='中央厨房项目名称')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
            ],
            options={
                'verbose_name': '中央厨房项目',
                'verbose_name_plural': '中央厨房项目',
            },
        ),
        migrations.CreateModel(
            name='CKProject2SDish2Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('B', '早餐'), ('L', '午餐'), ('D', '晚餐'), ('M', '夜餐')], default='L', max_length=1, verbose_name='用餐时间')),
                ('course', models.CharField(choices=[('PM', '主荤'), ('SM', '次荤'), ('VG', '素菜'), ('SP', '特色')], default='PM', max_length=2, verbose_name='菜品分类')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ckproject', verbose_name='中央厨房项目名称')),
            ],
            options={
                'verbose_name': '项目菜品',
                'verbose_name_plural': '项目菜品',
            },
        ),
        migrations.CreateModel(
            name='CKProjectLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='中央厨房餐点名称')),
            ],
            options={
                'verbose_name': '中央厨房餐点',
                'verbose_name_plural': '中央厨房餐点',
            },
        ),
        migrations.CreateModel(
            name='Condiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='调料名称')),
                ('price', models.FloatField(verbose_name='单价')),
            ],
            options={
                'verbose_name': '调料',
                'verbose_name_plural': '调料',
            },
        ),
        migrations.CreateModel(
            name='CongeeSoup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='汤粥名称')),
            ],
            options={
                'verbose_name': '汤粥',
                'verbose_name_plural': '汤粥',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='菜品名称')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
            },
        ),
        migrations.CreateModel(
            name='Disposable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='一次性用品名称')),
                ('price', models.FloatField(verbose_name='单价')),
            ],
            options={
                'verbose_name': '一次性用品',
                'verbose_name_plural': '一次性用品',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='配料名称')),
                ('ratio', models.FloatField(default=1, verbose_name='转化率')),
                ('price', models.FloatField(verbose_name='单价(元/斤)')),
            ],
            options={
                'verbose_name': '配菜',
                'verbose_name_plural': '配菜',
            },
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='油名称')),
                ('price', models.FloatField(verbose_name='单价')),
            ],
            options={
                'verbose_name': '油',
                'verbose_name_plural': '油',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('condiments_bool', models.BooleanField(verbose_name='点击使用此调料价格而非下面表格的调料明细')),
                ('condiments_price', models.FloatField(verbose_name='项目的调料价格')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='SDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='菜品名称')),
            ],
            options={
                'verbose_name': '标准化菜品',
                'verbose_name_plural': '标准化菜品',
            },
        ),
        migrations.CreateModel(
            name='SDish2Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=200, verbose_name='标准名称')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.sdish', verbose_name='菜品名称')),
            ],
            options={
                'verbose_name': '新菜品的标准',
                'verbose_name_plural': '新菜品的标准',
            },
        ),
        migrations.CreateModel(
            name='Staple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='主食名称')),
                ('price', models.FloatField(verbose_name='单价')),
            ],
            options={
                'verbose_name': '主食',
                'verbose_name_plural': '主食',
            },
        ),
        migrations.CreateModel(
            name='SuperProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='大项目名称')),
            ],
            options={
                'verbose_name': '大项目',
                'verbose_name_plural': '大项目',
            },
        ),
        migrations.CreateModel(
            name='SDish2StandardIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='重量')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient', verbose_name='配菜名称')),
                ('sdish2standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.sdish2standard')),
            ],
            options={
                'verbose_name': '此标准的配菜',
                'verbose_name_plural': '此标准的配菜',
            },
        ),
        migrations.CreateModel(
            name='Program2Staple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='用量')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.program', verbose_name='项目名称')),
                ('staple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.staple', verbose_name='主食名称')),
            ],
            options={
                'verbose_name': '项目的主食',
                'verbose_name_plural': '项目的主食',
            },
        ),
        migrations.CreateModel(
            name='Program2Oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='用量')),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.oil', verbose_name='油名称')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.program', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目的油',
                'verbose_name_plural': '项目的油',
            },
        ),
        migrations.CreateModel(
            name='Program2Disposable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='用量')),
                ('disposable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.disposable', verbose_name='一次性用品名称')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.program', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目的一次性用品',
                'verbose_name_plural': '项目的一次性用品',
            },
        ),
        migrations.CreateModel(
            name='Program2Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='份数')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish', verbose_name='菜品名称')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.program', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目的菜品',
                'verbose_name_plural': '项目的菜品',
            },
        ),
        migrations.CreateModel(
            name='Program2CongeeSoup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='份数')),
                ('congeesoup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.congeesoup', verbose_name='汤粥名称')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.program', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目的汤粥',
                'verbose_name_plural': '项目的汤粥',
            },
        ),
        migrations.CreateModel(
            name='Program2Condiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='用量')),
                ('condiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.condiment', verbose_name='调料名称')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.program', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目的调料',
                'verbose_name_plural': '项目的调料',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='condiments',
            field=models.ManyToManyField(through='menu.Program2Condiment', to='menu.Condiment'),
        ),
        migrations.AddField(
            model_name='program',
            name='congeesoups',
            field=models.ManyToManyField(through='menu.Program2CongeeSoup', to='menu.CongeeSoup'),
        ),
        migrations.AddField(
            model_name='program',
            name='dishes',
            field=models.ManyToManyField(through='menu.Program2Dish', to='menu.Dish'),
        ),
        migrations.AddField(
            model_name='program',
            name='disposables',
            field=models.ManyToManyField(through='menu.Program2Disposable', to='menu.Disposable'),
        ),
        migrations.AddField(
            model_name='program',
            name='oil',
            field=models.ManyToManyField(through='menu.Program2Oil', to='menu.Oil'),
        ),
        migrations.AddField(
            model_name='program',
            name='staples',
            field=models.ManyToManyField(through='menu.Program2Staple', to='menu.Staple'),
        ),
        migrations.AddField(
            model_name='program',
            name='superprogram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.superprogram', verbose_name='大项目名称'),
        ),
        migrations.CreateModel(
            name='Dish2Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='重量')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish', verbose_name='菜品名称')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient', verbose_name='配菜名称')),
            ],
            options={
                'verbose_name': '菜品的配菜',
                'verbose_name_plural': '菜品的配菜',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='menu.Dish2Ingredient', to='menu.Ingredient'),
        ),
        migrations.CreateModel(
            name='CongeeSoup2Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='重量')),
                ('congeesoup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.congeesoup', verbose_name='汤粥名称')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient', verbose_name='配菜名称')),
            ],
            options={
                'verbose_name': '汤粥的配菜',
                'verbose_name_plural': '汤粥的配菜',
            },
        ),
        migrations.AddField(
            model_name='congeesoup',
            name='ingredient',
            field=models.ManyToManyField(through='menu.CongeeSoup2Ingredient', to='menu.Ingredient'),
        ),
        migrations.CreateModel(
            name='CKProject2SDish2StandardCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='份数')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ckprojectlocation', verbose_name='送餐点')),
                ('project2dish2standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ckproject2sdish2standard')),
            ],
            options={
                'verbose_name': '送餐点及份数',
                'verbose_name_plural': '送餐点及份数',
            },
        ),
        migrations.AddField(
            model_name='ckproject2sdish2standard',
            name='sdish2standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.sdish2standard', verbose_name='菜品名称'),
        ),
        migrations.AddField(
            model_name='ckproject',
            name='sdishe2standards',
            field=models.ManyToManyField(through='menu.CKProject2SDish2Standard', to='menu.SDish2Standard'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='program-name-date-unique'),
        ),
    ]
