# Generated by Django 2.2.4 on 2021-05-19 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='日期'),
        ),
    ]
