# Generated by Django 2.2.4 on 2020-02-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(verbose_name='单价(元/克)'),
        ),
    ]
