# Generated by Django 2.2.4 on 2021-05-19 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210519_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='日期'),
        ),
    ]
