# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160809_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ratio',
            field=models.FloatField(default=1),
        ),
    ]
