# Generated by Django 3.2.7 on 2021-10-23 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_ckproject2sdish2standard_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.project')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderSummaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='重量')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingredient')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.purchaseordersummary')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='重量')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingredient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.projectpurchaseorder')),
            ],
        ),
    ]
