# Generated by Django 2.0.1 on 2018-06-04 02:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20170111_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Program2Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Dish')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Program')),
            ],
        ),
        migrations.AlterField(
            model_name='dish2ingredient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='program',
            name='dishes',
            field=models.ManyToManyField(through='menu.Program2Dish', to='menu.Dish'),
        ),
    ]
