# Generated by Django 3.2.7 on 2021-10-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_project_projectpurchaseorder_projectpurchaseorderitem_purchaseordersummary_purchaseordersummaryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': '原材料', 'verbose_name_plural': '原材料'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='projectpurchaseorder',
            options={'verbose_name': '项目采购清单', 'verbose_name_plural': '项目采购清单'},
        ),
        migrations.AlterModelOptions(
            name='projectpurchaseorderitem',
            options={'verbose_name': '项目采购物', 'verbose_name_plural': '项目采购物'},
        ),
        migrations.AlterModelOptions(
            name='sdish2standardingredient',
            options={'verbose_name': '此标准的原材料', 'verbose_name_plural': '此标准的原材料'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('VG', '蔬菜'), ('MT', '肉类'), ('CND', '调料'), ('RNO', '米面油'), ('DSP', '低值易耗')], default='VG', max_length=3, verbose_name='原材料分类'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='原材料名称'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(verbose_name='单价(元/斤或个)'),
        ),
        migrations.AlterField(
            model_name='projectpurchaseorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectpurchaseorderitem',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingredient', verbose_name='原材料'),
        ),
        migrations.AlterField(
            model_name='sdish2standardingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient', verbose_name='原材料名称'),
        ),
    ]
