# Generated by Django 2.0.7 on 2018-07-06 10:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20180604_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': '菜品', 'verbose_name_plural': '菜品'},
        ),
        migrations.AlterModelOptions(
            name='dish2ingredient',
            options={'verbose_name': '菜品的配料', 'verbose_name_plural': '菜品的配料'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': '配料', 'verbose_name_plural': '配料'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='program2dish',
            options={'verbose_name': '项目的菜品', 'verbose_name_plural': '项目的菜品'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='菜品名称'),
        ),
        migrations.AlterField(
            model_name='dish2ingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Dish', verbose_name='菜品名称'),
        ),
        migrations.AlterField(
            model_name='dish2ingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Ingredient', verbose_name='配料名称'),
        ),
        migrations.AlterField(
            model_name='dish2ingredient',
            name='quantity',
            field=models.FloatField(verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='配料名称'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(verbose_name='单价(元/斤)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ratio',
            field=models.FloatField(default=1, verbose_name='转化率'),
        ),
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='program2dish',
            name='count',
            field=models.IntegerField(verbose_name='份数'),
        ),
        migrations.AlterField(
            model_name='program2dish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Dish', verbose_name='菜品名称'),
        ),
        migrations.AlterField(
            model_name='program2dish',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Program', verbose_name='项目名称'),
        ),
    ]
