# Generated by Django 3.2.7 on 2021-11-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20211025_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ckproject',
            options={'verbose_name': '中央厨房菜单', 'verbose_name_plural': '                                                                                               中央厨房菜单'},
        ),
        migrations.AlterModelOptions(
            name='ckprojectlocation',
            options={'verbose_name': '中央厨房送餐点', 'verbose_name_plural': '                                                                                                中央厨房送餐点'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': '原材料', 'verbose_name_plural': '                                                                                                   原材料'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '                                                                                                 项目'},
        ),
        migrations.AlterModelOptions(
            name='projectpurchaseorder',
            options={'verbose_name': '项目采购清单', 'verbose_name_plural': '                                                                                              项目采购清单'},
        ),
        migrations.AlterModelOptions(
            name='projectpurchaseorderitem',
            options={'verbose_name': '项目采购品', 'verbose_name_plural': '项目采购品'},
        ),
        migrations.AlterModelOptions(
            name='purchaseordersummary',
            options={'verbose_name': '采购清单汇总', 'verbose_name_plural': '                                                                                             采购清单汇总'},
        ),
        migrations.AlterModelOptions(
            name='purchaseordersummaryitem',
            options={'verbose_name': '采购品', 'verbose_name_plural': '采购品'},
        ),
        migrations.AlterModelOptions(
            name='sdish',
            options={'verbose_name': '菜品', 'verbose_name_plural': '                                                                                                  菜品'},
        ),
        migrations.RemoveField(
            model_name='ckproject',
            name='name',
        ),
        migrations.AddField(
            model_name='ckproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.project', verbose_name='中央厨房项目名称'),
        ),
        migrations.AlterField(
            model_name='ckprojectlocation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='中央厨房送餐点名称'),
        ),
        migrations.AlterField(
            model_name='projectpurchaseorderitem',
            name='quantity',
            field=models.FloatField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='purchaseordersummaryitem',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient', verbose_name='原材料'),
        ),
        migrations.AlterField(
            model_name='purchaseordersummaryitem',
            name='quantity',
            field=models.FloatField(verbose_name='数量'),
        ),
    ]
