# Generated by Django 3.2.7 on 2021-11-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20211124_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.project', verbose_name='中央厨房项目名称'),
        ),
    ]
